fix: Update to MorphoCloud/MorphoCloudWorkflow@624549e
List of MorphoCloudWorkflow changes:

```
$ git shortlog 153894b..624549e --no-merges
Jean-Christophe Fillion-Robin (8):
      doc: Add MAINTENANCE.md document
      fix(collect-instance-uptime): Run every 15 minutes (instead of every 5)
      fix(ISSUE_TEMPLATE/config.yml): Allow blank issue
      fix(noxfile): Ensure blank issue template is disabled in target project
      fix(create-ip): Ensure "floating_ip_uuid" is set for retrieved floating IP
      fix(create-ip): Ensure "floating_ip_uuid" output is set
      fix(control-instance): Correct logic for checking assigned floating IP
      fix(control-instance): Fix logic discarding previously assigned IP

dependabot[bot] (2):
      chore(deps): Bump actions/create-github-app-token from 1.11.5 to 1.11.6
      chore(deps): Bump actions/create-github-app-token from 1.11.6 to 1.12.0

muratmaga (3):
      fix(cloud-config): Update to MorphoCloud/exosphere@28525e5d6
      fix(cloud-config): Update to MorphoCloud/exosphere@2229c5b57
      fix(cloud-config): Update to MorphoCloud/exosphere@1c229b4c2
```

See https://github.com/MorphoCloud/MorphoCloudWorkflow/compare/153894b...624549e

diff --git a/.github/workflows/automatic-instance-deleting.yml b/.github/workflows/automatic-instance-deleting.yml
--- a/.github/workflows/automatic-instance-deleting.yml
+++ b/.github/workflows/automatic-instance-deleting.yml
@@ -19,7 +19,7 @@ jobs:
     steps:
       - uses: actions/checkout@v4
 
-      - uses: actions/create-github-app-token@0d564482f06ca65fa9e77e2510873638c82206f2 # v1.11.5
+      - uses: actions/create-github-app-token@d72941d797fd3113feb6b93fd0dec494b13a2547 # v1.12.0
         id: app-token
         with:
           app-id: ${{ vars.MORPHOCLOUD_WORKFLOW_APP_ID }}
@@ -74,7 +74,18 @@ jobs:
 
               if [[ "$days_until_expiration" -le 0 ]]; then
                 echo "Instance ${instance_name} has expired. Deleting..."
-                gh issue comment "$issue_number" --body "/delete_instance"
+                set +e
+                gh workflow run control-instance-from-workflow.yml \
+                  -f issue_number=$issue_number \
+                  -f command_name=delete
+                  error_code=$?
+                set -e
+                if [[ $error_code -ne 0 ]]; then
+                  echo "::warning ::Failed to run workflow for deleting $instance_name."
+                  gh issue comment "$issue_number" \
+                    --body "❌ Failed to delete instance. See details at https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
+                  continue
+                fi
                 gh issue edit $issue_number --add-label "volume:expiration-pending"
 
               elif [[ "$days_until_expiration" -le $EXPIRATION_WARNING_DAYS ]]; then
diff --git a/.github/workflows/automatic-volume-deleting.yml b/.github/workflows/automatic-volume-deleting.yml
--- a/.github/workflows/automatic-volume-deleting.yml
+++ b/.github/workflows/automatic-volume-deleting.yml
@@ -48,7 +48,7 @@ jobs:
 
       - uses: actions/checkout@v4
 
-      - uses: actions/create-github-app-token@0d564482f06ca65fa9e77e2510873638c82206f2 # v1.11.5
+      - uses: actions/create-github-app-token@d72941d797fd3113feb6b93fd0dec494b13a2547 # v1.12.0
         id: app-token
         with:
           app-id: ${{ vars.MORPHOCLOUD_WORKFLOW_APP_ID }}
@@ -137,7 +137,16 @@ jobs:
 
             if [[ "$days_until_expiration" -le 0 ]]; then
               echo "🚨 Volume ${volume_name} has expired. Deleting..."
-              gh issue comment "$issue_number" --body "/delete_volume"
+              gh workflow run delete-volume-from-workflow.yml \
+                -f issue_number=$issue_number
+                error_code=$?
+              set -e
+              if [[ $error_code -ne 0 ]]; then
+                echo "::warning ::Failed to run workflow for deleting $volume_name."
+                gh issue comment "$issue_number" \
+                  --body "❌ Failed to delete volume <tt>$volume_name</tt>. See details at https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
+                continue
+              fi
               gh issue edit "$issue_number" --remove-label "volume:expiration-pending"
             else
               echo "ℹ️ Volume [$volume_name] still has [$days_until_expiration] days before deletion."
