fix: Update to MorphoCloud/MorphoCloudWorkflow@8bdc78d
List of MorphoCloudWorkflow changes:

```
$ git shortlog bf379a6..8bdc78d --no-merges
Jean-Christophe Fillion-Robin (1):
      fix(create-instance): Report creation error in failure comment
```

See https://github.com/MorphoCloud/MorphoCloudWorkflow/compare/bf379a6...8bdc78d

diff --git a/.github/workflows/create-instance.yml b/.github/workflows/create-instance.yml
--- a/.github/workflows/create-instance.yml
+++ b/.github/workflows/create-instance.yml
@@ -207,7 +207,8 @@ jobs:
           # Update INSTANCE_FAVOR placeholder to ensure current value is passed to ansible
           sed -i 's/INSTANCE_FLAVOR/$INSTANCE_FLAVOR/g' ./cloud-config
 
-          openstack server create "$INSTANCE_NAME" \
+          set +e
+          output_message=$(openstack server create "$INSTANCE_NAME" \
             --nic net-id="auto_allocated_network" \
             --security-group "exosphere" \
             --flavor $INSTANCE_FLAVOR \
@@ -226,8 +227,17 @@ jobs:
             --column flavor \
             --column image \
             --column name \
-            --column status
+            --column status 2>&1)
+          error_code=$?
+          set -e
 
+          echo "output_message [$output_message]"
+          echo "output_message=$output_message" >> $GITHUB_OUTPUT
+
+          if [[ $error_code -ne 0 ]]; then
+              echo "::error ::Failed to create instance 'INSTANCE_NAME': $output_message"
+              exit 1
+          fi
         env:
           OS_CLOUD: ${{ vars.MORPHOCLOUD_OS_CLOUD }}
           INSTANCE_NAME: ${{ steps.define.outputs.instance_name }}
@@ -242,7 +252,7 @@ jobs:
           body: |
             ### Instance Creation Results ❌
 
-            Failed to create instance **${{ steps.define.outputs.instance_name }}**.
+            Failed to create instance **${{ steps.define.outputs.instance_name }}**: ${{ steps.create_instance.outputs.output_message }}.
 
             See details at https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
 
