fix: Update to MorphoCloud/MorphoCloudWorkflow@0439a5b
List of MorphoCloudWorkflow changes:

```
$ git shortlog e357cda..0439a5b --no-merges
Jean-Christophe Fillion-Robin (10):
      feat(send-email): Update email body to describe TurboVNC connection
      fix(send-email): Update notes describing session timeout and how to extend
      fix(cloud-config): Update to MorphoCloud/exosphere@3ffe2e6a5
      doc(MAINTENANCE): Provide example in target repositories in "Vendoring `exosphere`" section
      doc(MAINTENANCE): Fix "Vendoring `exosphere`" section to ensure MorphoCloudWorkflow is updated
      chore(validate-request): Fix typo emojii -> emoji
      chore(README): Remove extra empty lines anticipating "mirrors-prettier" update
      chore: Update pre-commit hooks
      chore(gitgnore): Add node_modules/ directory created when locally running pre-commit
      feat: enforce approval-based access control for instance and volume management

dependabot[bot] (1):
      chore(deps): Bump dawidd6/action-send-mail from 5 to 6
```

See https://github.com/MorphoCloud/MorphoCloudWorkflow/compare/e357cda...0439a5b

diff --git a/.github/workflows/create-instance.yml b/.github/workflows/create-instance.yml
--- a/.github/workflows/create-instance.yml
+++ b/.github/workflows/create-instance.yml
@@ -18,21 +18,64 @@ jobs:
           command: "/create"
           reaction: "rocket"
           allowed_contexts: "issue"
-          permissions: "write,maintain,admin"
-          allowlist: "${{ vars.MORPHOCLOUD_GITHUB_ADMINS }}"
+          permissions: "read,triage,write,maintain,admin"
+          allowlist:
+            "${{ vars.MORPHOCLOUD_GITHUB_ADMINS }},${{
+            github.event.issue.user.login }}"
 
       - uses: actions/checkout@v4
 
-      - name: Add "request:approved" label
+      - name:
+          Convenienty add "request:approved" label if comment added by an admin
         uses: actions/github-script@v7
         with:
           script: |
-            github.rest.issues.addLabels({
-              issue_number: context.payload.issue.number,
-              owner: context.repo.owner,
-              repo: context.repo.repo,
-              labels: ["request:approved"]
-            })
+            const admins = process.env.MORPHOCLOUD_GITHUB_ADMINS.split(',').map(s => s.trim());
+            const actor = context.payload.comment.user.login;
+            if (admins.includes(actor)) {
+              await github.rest.issues.addLabels({
+                issue_number: context.payload.issue.number,
+                owner: context.repo.owner,
+                repo: context.repo.repo,
+                labels: ["request:approved"]
+              });
+            } else {
+              core.info(`${actor} is not in the list of admins`);
+            }
+        env:
+          MORPHOCLOUD_GITHUB_ADMINS: ${{ vars.MORPHOCLOUD_GITHUB_ADMINS }}
+
+      - name: Define instance name
+        id: define
+        uses: ./.github/actions/define-instance-name
+        with:
+          prefix: ${{ vars.INSTANCE_NAME_PREFIX }}
+          issue_number: ${{ github.event.issue.number }}
+
+      - name: Check instance management approval
+        id: check_approval
+        uses: ./.github/actions/check-approval
+        with:
+          token: ${{ secrets.GITHUB_TOKEN }}
+          issue_number: ${{ github.event.issue.number }}
+
+      - name: command results comment (Instance management not approved)
+        if: ${{ ! fromJSON(steps.check_approval.outputs.is_approved) }}
+        uses: peter-evans/create-or-update-comment@v4.0.0
+        with:
+          issue-number: ${{ github.event.issue.number }}
+          body: |
+            ### Command Results ❌
+
+            `/create` command failed because management of **${{ steps.define.outputs.instance_name }}** has not been approved yet.
+
+      - name: instance management not approved (failure)
+        if: ${{ ! fromJSON(steps.check_approval.outputs.is_approved) }}
+        run: |
+          echo "::error ::Instance $INSTANCE_NAME management not approved"
+          exit 1
+        env:
+          INSTANCE_NAME: ${{ steps.define.outputs.instance_name }}
 
       - name: comment (progress)
         id: couc_progress
@@ -60,13 +103,6 @@ jobs:
           GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           GH_REPO: ${{ github.repository }}
           ISSUE_NUMBER: ${{ github.event.issue.number }}
-
-      - name: Define instance name
-        id: define
-        uses: ./.github/actions/define-instance-name
-        with:
-          prefix: ${{ vars.INSTANCE_NAME_PREFIX }}
-          issue_number: ${{ github.event.issue.number }}
 
       - name: Check instance exists
         id: check_instance
@@ -326,15 +362,6 @@ jobs:
                   echo "Exiting loop."
                   break
               else
-                  instance_status=$(openstack server show $INSTANCE_NAME -c status -f json | \
-                    jq -r '.status')
-                  echo "instance_status [$instance_status]"
-                  if [[ "$STATUS" == "ERROR" ]]; then
-                      echo "status=error" >> $GITHUB_OUTPUT
-                      echo "::error ::Failed to create instance '$INSTANCE_NAME'."
-                      exit 1
-                  fi
-
                   echo "Waiting for completion..."
                   sleep $wait_interval
                   total_wait_time=$((total_wait_time + wait_interval))
@@ -342,7 +369,6 @@ jobs:
           done
 
           if [ $total_wait_time -ge $max_wait_time ]; then
-              echo "status=polling-timeout" >> $GITHUB_OUTPUT
               echo "::error ::Maximum wait time ($max_wait_time seconds) exceeded."
               exit 1
           fi
@@ -360,9 +386,7 @@ jobs:
           INSTANCE_NAME: ${{ steps.define.outputs.instance_name }}
 
       - name: comment (maximum wait time exceeded)
-        if:
-          ${{ steps.instance_poll.outputs.status == 'polling-timeout' &&
-          steps.instance_poll.outcome == 'failure' && failure() }}
+        if: ${{ steps.instance_poll.outcome == 'failure' && failure() }}
         uses: peter-evans/create-or-update-comment@v4.0.0
         with:
           issue-number: ${{ github.event.issue.number }}
@@ -370,20 +394,6 @@ jobs:
             ### Instance Creation Results ❌
 
             Maximum wait time for instance **${{ steps.define.outputs.instance_name }}** setup to complete exceeded.
-
-            See details at https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
-
-      - name: comment (instance creation failed)
-        if:
-          ${{ steps.instance_poll.outputs.status == 'error' &&
-          steps.instance_poll.outcome == 'failure' && failure() }}
-        uses: peter-evans/create-or-update-comment@v4.0.0
-        with:
-          issue-number: ${{ github.event.issue.number }}
-          body: |
-            ### Instance Creation Results ❌
-
-            Failed to create instance **${{ steps.define.outputs.instance_name }}**.
 
             See details at https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
 
